<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jsonata.Net.Native\Jsonata.Net.Native.csproj" />
  </ItemGroup>
</Project>
